import type { FeedbackEntry, Group, ReportEntry, TalahRequest, User } from "./types";

const now = Date.now();
const day = 24 * 60 * 60 * 1000;

export const SEED_USERS: User[] = [
  {
    id: "u1",
    phone: "+966500000001",
    nickname: "ريم",
    gender: "woman",
    city: "الرياض",
    ageRange: "25-29",
    lifestyle: "employee",
    interests: ["coffee", "books", "wellness", "self_development"],
    personality: "calm",
    preferredMeetup: "coffee",
    preferredDays: ["sat", "sun", "thu"],
    preferredTimes: ["morning", "evening"],
    funFact: "أحفظ ٢٠٠ حساب قهوة على إنستقرام",
    verified: true,
    flagged: false,
    onboarded: true,
    createdAt: now - 30 * day,
  },
  {
    id: "u2",
    phone: "+966500000002",
    nickname: "نورة",
    gender: "woman",
    city: "الرياض",
    ageRange: "25-29",
    lifestyle: "entrepreneur",
    interests: ["business", "coffee", "self_development", "art"],
    personality: "curious",
    preferredMeetup: "coffee",
    preferredDays: ["sat", "thu"],
    preferredTimes: ["morning"],
    funFact: "أبني علامتي التجارية الخاصة",
    verified: true,
    flagged: false,
    onboarded: true,
    createdAt: now - 25 * day,
  },
  {
    id: "u3",
    phone: "+966500000003",
    nickname: "لمى",
    gender: "woman",
    city: "الرياض",
    ageRange: "30-34",
    lifestyle: "parent",
    interests: ["wellness", "outdoor", "food", "books"],
    personality: "social",
    preferredMeetup: "coffee",
    preferredDays: ["sat"],
    preferredTimes: ["morning"],
    funFact: "أمشي ٥ كم يوميًا قبل القهوة",
    verified: false,
    flagged: false,
    onboarded: true,
    createdAt: now - 18 * day,
  },
  {
    id: "u4",
    phone: "+966500000004",
    nickname: "سارة",
    gender: "woman",
    city: "جدة",
    ageRange: "30-34",
    lifestyle: "employee",
    interests: ["art", "food", "wellness", "self_development"],
    personality: "creative",
    preferredMeetup: "dinner",
    preferredDays: ["wed", "thu"],
    preferredTimes: ["evening"],
    funFact: "أرسم على الزجاج في وقتي الحر",
    verified: true,
    flagged: false,
    onboarded: true,
    createdAt: now - 14 * day,
  },
  {
    id: "u5",
    phone: "+966500000005",
    nickname: "هند",
    gender: "woman",
    city: "جدة",
    ageRange: "25-29",
    lifestyle: "student",
    interests: ["books", "art", "self_development"],
    personality: "calm",
    preferredMeetup: "coffee",
    preferredDays: ["sun", "tue"],
    preferredTimes: ["afternoon"],
    funFact: "أكتب مذكرات يومية منذ ١٠ سنوات",
    verified: false,
    flagged: false,
    onboarded: true,
    createdAt: now - 10 * day,
  },
  {
    id: "u6",
    phone: "+966500000006",
    nickname: "دانة",
    gender: "woman",
    city: "الدمام",
    ageRange: "30-34",
    lifestyle: "entrepreneur",
    interests: ["business", "fitness", "food"],
    personality: "active",
    preferredMeetup: "dinner",
    preferredDays: ["wed", "thu"],
    preferredTimes: ["evening"],
    funFact: "أحب الجري على الكورنيش فجرًا",
    verified: true,
    flagged: false,
    onboarded: true,
    createdAt: now - 8 * day,
  },
  {
    id: "u7",
    phone: "+966500000007",
    nickname: "عبدالله",
    gender: "man",
    city: "الرياض",
    ageRange: "25-29",
    lifestyle: "employee",
    interests: ["coffee", "business", "self_development"],
    personality: "calm",
    preferredMeetup: "coffee",
    preferredDays: ["sat", "thu"],
    preferredTimes: ["morning"],
    funFact: "أصنع قهوتي بطريقة الـ V60",
    verified: true,
    flagged: false,
    onboarded: true,
    createdAt: now - 22 * day,
  },
  {
    id: "u8",
    phone: "+966500000008",
    nickname: "محمد",
    gender: "man",
    city: "الرياض",
    ageRange: "25-29",
    lifestyle: "entrepreneur",
    interests: ["business", "outdoor", "fitness"],
    personality: "active",
    preferredMeetup: "coffee",
    preferredDays: ["sat"],
    preferredTimes: ["morning"],
    funFact: "أتسلق الجبال في عطلتي",
    verified: true,
    flagged: false,
    onboarded: true,
    createdAt: now - 20 * day,
  },
  {
    id: "u9",
    phone: "+966500000009",
    nickname: "فيصل",
    gender: "man",
    city: "الرياض",
    ageRange: "30-34",
    lifestyle: "employee",
    interests: ["books", "self_development", "art"],
    personality: "curious",
    preferredMeetup: "coffee",
    preferredDays: ["thu"],
    preferredTimes: ["evening"],
    funFact: "أقرأ كتابًا كل أسبوع",
    verified: false,
    flagged: false,
    onboarded: true,
    createdAt: now - 16 * day,
  },
  {
    id: "u10",
    phone: "+966500000010",
    nickname: "ياسر",
    gender: "man",
    city: "جدة",
    ageRange: "30-34",
    lifestyle: "parent",
    interests: ["food", "outdoor", "wellness"],
    personality: "social",
    preferredMeetup: "dinner",
    preferredDays: ["wed", "thu"],
    preferredTimes: ["evening"],
    funFact: "أطبخ المندي بطريقتي الخاصة",
    verified: true,
    flagged: false,
    onboarded: true,
    createdAt: now - 12 * day,
  },
  {
    id: "u11",
    phone: "+966500000011",
    nickname: "سعد",
    gender: "man",
    city: "جدة",
    ageRange: "25-29",
    lifestyle: "student",
    interests: ["fitness", "outdoor", "self_development"],
    personality: "active",
    preferredMeetup: "dinner",
    preferredDays: ["wed"],
    preferredTimes: ["evening"],
    funFact: "أتدرب للماراثون",
    verified: false,
    flagged: false,
    onboarded: true,
    createdAt: now - 9 * day,
  },
  {
    id: "u12",
    phone: "+966500000012",
    nickname: "خالد",
    gender: "man",
    city: "الدمام",
    ageRange: "35-44",
    lifestyle: "entrepreneur",
    interests: ["business", "coffee", "books"],
    personality: "calm",
    preferredMeetup: "coffee",
    preferredDays: ["sat", "thu"],
    preferredTimes: ["morning"],
    funFact: "أؤسس مقهى صغيرًا في الخبر",
    verified: true,
    flagged: false,
    onboarded: true,
    createdAt: now - 7 * day,
  },
];

export const SEED_REQUESTS: TalahRequest[] = [
  {
    id: "r1",
    userId: "u1",
    meetupType: "coffee",
    preferredDate: new Date(now + 3 * day).toISOString().slice(0, 10),
    preferredTime: "morning",
    area: "العليا",
    status: "matched",
    createdAt: now - 2 * day,
    groupId: "g1",
  },
  {
    id: "r2",
    userId: "u2",
    meetupType: "coffee",
    preferredDate: new Date(now + 3 * day).toISOString().slice(0, 10),
    preferredTime: "morning",
    area: "العليا",
    status: "matched",
    createdAt: now - 2 * day,
    groupId: "g1",
  },
  {
    id: "r3",
    userId: "u3",
    meetupType: "coffee",
    preferredDate: new Date(now + 3 * day).toISOString().slice(0, 10),
    preferredTime: "morning",
    area: "العليا",
    status: "matched",
    createdAt: now - 2 * day,
    groupId: "g1",
  },
  {
    id: "r4",
    userId: "u7",
    meetupType: "coffee",
    preferredDate: new Date(now + 5 * day).toISOString().slice(0, 10),
    preferredTime: "morning",
    area: "حي السفارات",
    status: "pending",
    createdAt: now - 1 * day,
  },
  {
    id: "r5",
    userId: "u8",
    meetupType: "coffee",
    preferredDate: new Date(now + 5 * day).toISOString().slice(0, 10),
    preferredTime: "morning",
    area: "حي السفارات",
    status: "pending",
    createdAt: now - 1 * day,
  },
];

export const SEED_GROUPS: Group[] = [
  {
    id: "g1",
    status: "matched",
    meetupType: "coffee",
    gender: "woman",
    city: "الرياض",
    area: "العليا",
    venue: "مقهى مدد - العليا",
    meetupAt: now + 3 * day,
    memberIds: ["u1", "u2", "u3"],
    requestIds: ["r1", "r2", "r3"],
    createdAt: now - 1 * day,
  },
];

export const SEED_FEEDBACK: FeedbackEntry[] = [];
export const SEED_REPORTS: ReportEntry[] = [];
