/**
 * Seed women compatible with Aziz (فce34802… / الدمام / 25-29 / coffee).
 * Match criteria:
 *  - gender: woman, city: الدمام
 *  - preferredDays includes Thursday (like Aziz)
 *  - preferredTimes includes afternoon
 *  - socialIntent: casual_conversations (same)
 *  - socialEnergy: quiet_open_later / ambivert range
 *  - conversationStyle: deep_meaningful
 *  - scores close to Aziz: energy≈-1, depth≈1, planning≈-1
 */

import { db, pool, usersTable, requestsTable } from "@workspace/db";

const AZIZ_ID = "fce34802-2ef2-4a6f-abdd-780c8172c39a";

const candidates = [
  {
    nickname: "رند",
    age_range: "25-29",
    lifestyle: "employee",
    personality: "creative",
    interests: ["fitness", "art", "reading"],
    enjoyedTopics: ["wellness_growth", "creative_arts"],
    socialEnergy: "quiet_open_later",
    conversationStyle: "deep_meaningful",
    socialIntent: "casual_conversations",
    planningPreference: "spontaneous",
    meetupAtmosphere: "moderate_energy",
    interactionPreference: "mix_conversation_activity",
    personalityTraits: ["curious", "empathetic", "creative"],
    opennessLevel: "open_gradually",
    socialBoundary: "respectful_balanced",
    preferredDays: ["thu", "fri"],
    preferredTimes: ["afternoon"],
    funFact: "أرسم بورتريهات بالقهوة بدلاً من الألوان",
    socialEnergyScore: -1,
    conversationDepthScore: 1,
    planningScore: -1,
    atmosphereScore: 0,
    interactionScore: 0,
    opennessScore: 0,
    boundaryScore: 0,
  },
  {
    nickname: "لجين",
    age_range: "25-29",
    lifestyle: "student",
    personality: "curious",
    interests: ["art", "wellness", "languages"],
    enjoyedTopics: ["wellness_growth", "personal_development"],
    socialEnergy: "quiet_open_later",
    conversationStyle: "deep_meaningful",
    socialIntent: "casual_conversations",
    planningPreference: "flexible",
    meetupAtmosphere: "low_key_comfortable",
    interactionPreference: "small_group",
    personalityTraits: ["curious", "social", "independent"],
    opennessLevel: "open_gradually",
    socialBoundary: "respectful_balanced",
    preferredDays: ["thu", "sat"],
    preferredTimes: ["afternoon", "evening"],
    funFact: "تعلمت الفرنسية من أفلام كرتونية",
    socialEnergyScore: -1,
    conversationDepthScore: 2,
    planningScore: 0,
    atmosphereScore: -1,
    interactionScore: -1,
    opennessScore: 0,
    boundaryScore: 0,
  },
  {
    nickname: "دانة",
    age_range: "30-34",
    lifestyle: "other",
    personality: "calm",
    interests: ["fitness", "reading", "design"],
    enjoyedTopics: ["wellness_growth", "creative_arts"],
    socialEnergy: "ambivert",
    conversationStyle: "deep_meaningful",
    socialIntent: "casual_conversations",
    planningPreference: "spontaneous",
    meetupAtmosphere: "moderate_energy",
    interactionPreference: "mix_conversation_activity",
    personalityTraits: ["empathetic", "calm", "energetic"],
    opennessLevel: "open_gradually",
    socialBoundary: "flexible_respectful",
    preferredDays: ["thu"],
    preferredTimes: ["afternoon"],
    funFact: "أمارس اليوجا على شاطئ كورنيش الدمام كل جمعة",
    socialEnergyScore: 0,
    conversationDepthScore: 1,
    planningScore: -1,
    atmosphereScore: 0,
    interactionScore: 0,
    opennessScore: 1,
    boundaryScore: 1,
  },
  {
    nickname: "شذى",
    age_range: "25-29",
    lifestyle: "entrepreneur",
    personality: "creative",
    interests: ["business", "art", "travel"],
    enjoyedTopics: ["wellness_growth", "entrepreneurship"],
    socialEnergy: "quiet_open_later",
    conversationStyle: "deep_meaningful",
    socialIntent: "casual_conversations",
    planningPreference: "spontaneous",
    meetupAtmosphere: "moderate_energy",
    interactionPreference: "mix_conversation_activity",
    personalityTraits: ["curious", "ambitious", "creative"],
    opennessLevel: "open_gradually",
    socialBoundary: "respectful_balanced",
    preferredDays: ["thu", "wed"],
    preferredTimes: ["afternoon", "morning"],
    funFact: "أطلقت متجر عبايات تصميمي قبل التخرج",
    socialEnergyScore: -1,
    conversationDepthScore: 1,
    planningScore: -2,
    atmosphereScore: 0,
    interactionScore: 1,
    opennessScore: 0,
    boundaryScore: 0,
  },
  {
    nickname: "نوف",
    age_range: "25-29",
    lifestyle: "employee",
    personality: "social",
    interests: ["fitness", "cooking", "art"],
    enjoyedTopics: ["wellness_growth", "lifestyle"],
    socialEnergy: "quiet_open_later",
    conversationStyle: "deep_meaningful",
    socialIntent: "casual_conversations",
    planningPreference: "flexible",
    meetupAtmosphere: "moderate_energy",
    interactionPreference: "mix_conversation_activity",
    personalityTraits: ["social", "curious", "caring"],
    opennessLevel: "open_gradually",
    socialBoundary: "respectful_balanced",
    preferredDays: ["thu", "fri"],
    preferredTimes: ["afternoon"],
    funFact: "أعمل مديرة مشاريع وأطبخ سوشي في عطلة نهاية الأسبوع",
    socialEnergyScore: -1,
    conversationDepthScore: 1,
    planningScore: 0,
    atmosphereScore: 0,
    interactionScore: 0,
    opennessScore: 0,
    boundaryScore: -1,
  },
  {
    nickname: "أسيل",
    age_range: "25-29",
    lifestyle: "student",
    personality: "curious",
    interests: ["art", "film", "wellness"],
    enjoyedTopics: ["creative_arts", "wellness_growth"],
    socialEnergy: "quiet_open_later",
    conversationStyle: "deep_meaningful",
    socialIntent: "casual_conversations",
    planningPreference: "spontaneous",
    meetupAtmosphere: "low_key_comfortable",
    interactionPreference: "one_on_one",
    personalityTraits: ["curious", "empathetic", "independent"],
    opennessLevel: "open_gradually",
    socialBoundary: "respectful_balanced",
    preferredDays: ["thu", "sun"],
    preferredTimes: ["afternoon", "evening"],
    funFact: "أكتب قصصاً قصيرة ونشرت إحداها في مجلة جامعية",
    socialEnergyScore: -2,
    conversationDepthScore: 2,
    planningScore: -1,
    atmosphereScore: -1,
    interactionScore: -1,
    opennessScore: 0,
    boundaryScore: 0,
  },
  {
    nickname: "غدير",
    age_range: "30-34",
    lifestyle: "employee",
    personality: "calm",
    interests: ["fitness", "design", "reading"],
    enjoyedTopics: ["wellness_growth", "professional_growth"],
    socialEnergy: "ambivert",
    conversationStyle: "deep_meaningful",
    socialIntent: "casual_conversations",
    planningPreference: "spontaneous",
    meetupAtmosphere: "moderate_energy",
    interactionPreference: "mix_conversation_activity",
    personalityTraits: ["calm", "curious", "ambitious"],
    opennessLevel: "open_gradually",
    socialBoundary: "flexible_respectful",
    preferredDays: ["thu", "sat"],
    preferredTimes: ["afternoon"],
    funFact: "أحب المشي لساعة يومياً بدون سماعات — أفضل وقت للتفكير",
    socialEnergyScore: 0,
    conversationDepthScore: 1,
    planningScore: -1,
    atmosphereScore: 1,
    interactionScore: 0,
    opennessScore: 0,
    boundaryScore: 1,
  },
  {
    nickname: "مها",
    age_range: "25-29",
    lifestyle: "other",
    personality: "creative",
    interests: ["art", "fitness", "photography"],
    enjoyedTopics: ["wellness_growth", "creative_arts"],
    socialEnergy: "quiet_open_later",
    conversationStyle: "deep_meaningful",
    socialIntent: "casual_conversations",
    planningPreference: "spontaneous",
    meetupAtmosphere: "moderate_energy",
    interactionPreference: "mix_conversation_activity",
    personalityTraits: ["creative", "curious", "energetic"],
    opennessLevel: "open_gradually",
    socialBoundary: "respectful_balanced",
    preferredDays: ["thu", "fri"],
    preferredTimes: ["afternoon", "morning"],
    funFact: "صورة التقطتها نشرتها حساب سياحي بـ 200 ألف متابع",
    socialEnergyScore: -1,
    conversationDepthScore: 1,
    planningScore: -1,
    atmosphereScore: 0,
    interactionScore: 0,
    opennessScore: 0,
    boundaryScore: 0,
  },
];

async function seed() {
  console.log("🌱 Seeding Aziz-compatible women in الدمام…");

  const rows = candidates.map((c, i) => ({
    phone: `+9665200${String(10 + i).padStart(2, "0")}999`,
    email: `compat-woman-${i}@talah-test.dev`,
    nickname: c.nickname,
    gender: "woman",
    city: "الدمام",
    ageRange: c.age_range,
    lifestyle: c.lifestyle,
    interests: c.interests,
    personality: c.personality,
    preferredMeetup: "coffee" as const,
    preferredDays: c.preferredDays,
    preferredTimes: c.preferredTimes,
    funFact: c.funFact,
    socialEnergy: c.socialEnergy,
    conversationStyle: c.conversationStyle,
    enjoyedTopics: c.enjoyedTopics,
    socialIntent: c.socialIntent,
    planningPreference: c.planningPreference,
    meetupAtmosphere: c.meetupAtmosphere,
    interactionPreference: c.interactionPreference,
    personalityTraits: c.personalityTraits,
    opennessLevel: c.opennessLevel,
    socialBoundary: c.socialBoundary,
    socialEnergyScore: c.socialEnergyScore,
    conversationDepthScore: c.conversationDepthScore,
    planningScore: c.planningScore,
    atmosphereScore: c.atmosphereScore,
    interactionScore: c.interactionScore,
    opennessScore: c.opennessScore,
    boundaryScore: c.boundaryScore,
    onboarded: true,
    verified: true,
    flagged: false,
    isAdmin: false,
  }));

  const inserted = await db
    .insert(usersTable)
    .values(rows)
    .returning({ id: usersTable.id, nickname: usersTable.nickname });

  console.log(`  ✓ ${inserted.length} users created`);

  // Give each a pending coffee request in الدمام on Thursday afternoon
  const requests = inserted.map((u) => ({
    userId: u.id,
    meetupType: "coffee" as const,
    preferredDate: "thursday",
    preferredTime: "afternoon",
    area: "الدمام",
    status: "pending",
  }));

  await db.insert(requestsTable).values(requests);
  console.log(`  ✓ ${requests.length} pending requests created`);

  console.log("\nUsers:");
  inserted.forEach((u) => console.log(`  ${u.nickname} (${u.id})`));
  console.log("\n✅ Done!");
  await pool.end();
}

seed().catch((err) => {
  console.error("Seed failed:", err);
  process.exit(1);
});
