uploads = []

[[generated]]
id = "z_HAA8NDfL1g3c8tUMP_x"
uri = "file://artifacts/talah/assets/images/icon.png"
type = "image"
title = "talah app icon"

[[generated]]
id = "YMl9x5mCMa3-egKHKdSEU"
uri = "file://artifacts/talah/assets/images/coffee-meetup.png"
type = "image"
title = "coffee meetup"

[[generated]]
id = "T9_aOv5U--_u1Y3SwQfPk"
uri = "file://artifacts/talah/assets/images/dinner-meetup.png"
type = "image"
title = "dinner meetup"

[[outputs]]
id = "j5BLUSpZqUpxucNU3htrY"
uri = "file://attached_assets/talah-dev-qr.png"
type = "image"
title = "Tal'ah Dev Preview QR Code"

[[outputs]]
id = "zbF_znXnfHvUaugJr2SNc"
uri = "file://.local/tmp-ios-signing/distribution_csr.zip"
type = "unspecified"
title = "iOS Distribution Certificate Signing Request (CSR)"

[[outputs]]
id = "22ABK6E5xJKXXU70RraYi"
uri = "file://.local/tmp-ios-signing/distribution.certSigningRequest.txt"
type = "text"
title = "Distribution CSR (rename to .certSigningRequest after download)"

[[outputs]]
id = "OOKjWKegdcCqFl2-UpIwn"
uri = "file://.local/tmp-ios-signing/distribution_p12.zip"
type = "unspecified"
title = "distribution.p12 (unzip to get the .p12 file)"

[[outputs]]
id = "5l4PqzdzPVJGIZggL8iiU"
uri = "file://.local/tmp-ios-signing/distribution_p12_base64.txt"
type = "text"
title = "distribution_p12_base64.txt (76-char wrapped)"
